### PR TITLE
removed code annotations, fixes #45

### LINKED ISSUE #45: comments in code
Hello, in the code examples (for example chapter 2), why is the code littered with comments such as:
 
<start id='"ch02_event_route'

Is there any reason for this? It is quite confusing when trying to understand the code, especially to a Scala beginner. Thanks.

### PR DESCRIPTION
**Pull request by kovszilard**
It is a simple regex search and replace on \*.scala and \*.sbt files
The regex used: //<[start|co|end].*/>

### CODE REVIEW

**Comment by RayRoestenburg** [comment]
@kovszilard Sorry there was an earlier PR outstanding, would you be able to rebase your changes?
I'll make sure I'll merge it once you have done that.

**Comment by kovszilard** [comment]
Done

**Comment by kovszilard** [comment]
Sorry, there were one extra comment. Now it is clean and mergeable.

**Comment by RayRoestenburg** [comment]
Thanks @kovszilard!

**Pull request merged**
